# Generated by Django 5.1.4 on 2024-12-20 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_optcg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='url',
            new_name='tcgUrl',
        ),
        migrations.CreateModel(
            name='Deck2Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_optcg.card')),
                ('deck_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_optcg.deck')),
            ],
            options={
                'ordering': ['deck_id'],
            },
        ),
    ]
